### GENERAL SETTINGS ###
name: "Blog"
description: "Basic Blog Strucre for Paxcel Technologies"
author: "vivek kumar"
email: webuimaker@gmail.com
url: ""
github : username
twitter : username
baseurl: /Blog
navigation:
 - title: Home
   url: /index.html
 - title: About Us
   url: /about.html
 - title: Category
   url: /category.html
 - title: Contact
   url: /contact.html
   
###disqus: jekyllblogsite

gems:
   - jekyll-paginate
   
### pagination
paginate: 4
paginate_path: "/blog/page:num/"
